# Taylor Cates
# Set of lines that make up each letter

import turtle
import turtlelines


def a():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.right_move(50)
    turtlelines.right_move(40)
    turtlelines.right_move(50)
    turtlelines.back_move(50)
    turtlelines.right_move(60)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)


def b():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.right_move(40)
    turtlelines.right_move(50)
    turtlelines.right_move(40)
    turtlelines.back_move(50)
    turtlelines.right_move(50)
    turtlelines.right_move(50)
    turtlelines.back_move(50)
    turtle.penup()
    turtle.forward(50)


def c():
    turtle.pendown()
    turtle.forward(50)
    turtlelines.back_move(50)
    turtlelines.right_move(100)
    turtlelines.right_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def d():
    turtle.pendown()
    turtle.forward(40)
    turtlelines.back_move(40)
    turtlelines.right_move(100)
    turtlelines.right_move(40)
    turtlelines.right_move(10)
    turtlelines.left_move(10)
    turtlelines.right_move(80)
    turtlelines.right_move(10)
    turtlelines.left_move(10)
    turtle.penup()
    turtlelines.left_move(50)


def e():
    turtle.pendown()
    turtle.forward(50)
    turtlelines.back_move(50)
    turtlelines.right_move(50)
    turtlelines.right_move(30)
    turtlelines.back_move(30)
    turtlelines.right_move(50)
    turtlelines.right_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def f():
    turtle.pendown()
    turtlelines.left_move(50)
    turtlelines.right_move(30)
    turtlelines.back_move(30)
    turtlelines.right_move(50)
    turtlelines.right_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def g():
    turtle.pendown()
    turtle.forward(50)
    turtlelines.left_move(40)
    turtlelines.left_move(20)
    turtle.penup()
    turtlelines.left_move(40)
    turtlelines.right_move(30)
    turtle.pendown()
    turtlelines.right_move(100)
    turtlelines.right_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def h():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.back_move(50)
    turtlelines.left_move(50)
    turtlelines.left_move(50)
    turtlelines.back_move(100)
    turtle.penup()
    turtlelines.left_move(50)


def i():
    turtle.pendown()
    turtle.forward(50)
    turtlelines.back_move(25)
    turtlelines.right_move(100)
    turtlelines.left_move(25)
    turtlelines.back_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def j():
    turtlelines.left_move(20)
    turtle.pendown()
    turtlelines.back_move(20)
    turtlelines.left_move(30)
    turtlelines.left_move(100)
    turtlelines.left_move(30)
    turtlelines.back_move(50)
    turtle.penup()
    turtlelines.right_move(100)
    turtlelines.left_move(50)


def k():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.back_move(50)
    turtlelines.left_move(30)
    turtlelines.left_move(10)
    turtlelines.right_move(10)
    turtlelines.left_move(10)
    turtlelines.right_move(10)
    turtlelines.left_move(30)
    turtle.penup()
    turtlelines.left_move(50)
    turtlelines.left_move(50)
    turtlelines.left_move(30)
    turtle.pendown()
    turtlelines.right_move(10)
    turtlelines.left_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.right_move(20)
    turtle.penup()
    turtlelines.left_move(50)


def l():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.back_move(100)
    turtlelines.left_move(50)
    turtle.penup()
    turtle.forward(50)


def m():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.right_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.left_move(20)
    turtlelines.right_move(10)
    turtlelines.left_move(20)
    turtlelines.right_move(10)
    turtlelines.right_move(100)
    turtle.penup()
    turtlelines.left_move(50)


def n():
    turtle.pendown()
    turtlelines.left_move(100)
    turtlelines.right_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.right_move(40)
    turtlelines.left_move(10)
    turtlelines.right_move(20)
    turtlelines.left_move(10)
    turtlelines.left_move(100)
    turtle.penup()
    turtlelines.back_move(100)
    turtlelines.left_move(50)


def o():
    turtle.forward(10)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.penup()
    turtle.forward(90)


def p():
    turtle.pendown()
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(100)


def q():
    turtle.forward(10)
    turtle.pendown()
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(80)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(180)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(20)
    turtle.penup()
    turtle.forward(50)


def r():
    turtle.pendown()
    turtle.left(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(180)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)


def s():
    turtle.pendown()
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(40)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)


def t():
    turtle.forward(25)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(180)
    turtle.forward(50)
    turtle.penup()
    turtle.right(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)


def u():
    turtle.left(90)
    turtle.forward(100)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(90)
    turtle.penup()
    turtle.right(180)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)


def v():
    turtle.left(90)
    turtle.forward(100)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(40)
    turtle.penup()
    turtle.right(180)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)


def w():
    turtle.left(90)
    turtle.forward(100)
    turtle.left(180)
    turtle.pendown()
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(180)
    turtle.penup()
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(50)


def x():
    turtle.pendown()
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.penup()
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.penup()
    turtle.forward(50)


def y():
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(50)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.penup()
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(50)
    turtle.penup()
    turtle.left(90)
    turtle.forward(75)


def z():
    turtle.pendown()
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.penup()
    turtle.forward(100)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(50)
    turtle.penup()
    turtle.forward(50)
